- changed-files:
    - any-glob-to-any-file: ["list", "of", "globs"]
    - any-glob-to-all-files: ["list", "of", "globs"]
    - all-globs-to-any-file: ["list", "of", "globs"]
    - all-globs-to-all-files: ["list", "of", "globs"]
